# Linux build configuration for Travis CI
dist: jammy

# Specify compilers
language: cpp
compiler: 
  - gcc
  - clang

# Install build dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential

# Build steps
script:
  - cmake -DCMAKE_BUILD_TYPE=Release -B ./build -S ./example
  - cmake --build ./build
